# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      docker system prune -a -f
    
- task: Docker@2
  inputs:
    containerRegistry: 'codeconvacr01-1931'
    repository: 'portal-backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'VerityStream-1308-Verity Production(caa88d8e-50da-4a07-9132-54b28d3060c7)'
    appType: 'webAppContainer'
    WebAppName: 'codeconv-priv-app01'
    deployToSlotOrASE: true
    ResourceGroupName: 'codeconv-rg01'
    SlotName: 'production'
    DockerNamespace: 'codeconvacr01.azurecr.io'
    DockerRepository: 'portal-backend'
    DockerImageTag: '$(Build.BuildId)'