# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'codeconvacr01-1931'
    repository: 'portal-backend'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile-appfunction-scheduler'
    tags: '1'

# - task: AzureFunctionApp@2
#   inputs:
#     connectedServiceNameARM: 'VerityStream-1308-Verity Production(caa88d8e-50da-4a07-9132-54b28d3060c7)'
#     appType: 'functionAppLinux'
#     appName: 
#     deployToSlotOrASE: true
#     slotName: 'production'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     deploymentMethod: 'auto'