# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'codeconvacr01-1931'
    repository: 'portal-backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '1'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'codeconv-rg01_serviceconnection'
    appType: 'webAppContainer'
    WebAppName: 'codeconv-app01'
    deployToSlotOrASE: true
    ResourceGroupName: 'codeconv-rg01'
    SlotName: 'production'
    DockerNamespace: 'codeconvacr01.azurecr.io'
    DockerRepository: 'portal-backend'
    DockerImageTag: '1'