# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:



- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'VerityStream-1308-Verity Production(caa88d8e-50da-4a07-9132-54b28d3060c7)'
    appType: 'functionAppLinux'
    appName: 'codeconv-pub-func04'
    deployToSlotOrASE: true
    resourceGroupName: 'codeconv-rg01'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/SchedulerProcessor/'
    runtimeStack: 'DOTNET|6.0'
    deploymentMethod: 'auto'

