# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'codeconvacr01-1931'
    repository: 'portal-backend'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile-appfunction-scheduler'
    tags: '1'

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'codeconv-rg01_serviceconnection'
    appType: 'functionAppLinux'
    appName: 'codeconv-func01'
    deployToSlotOrASE: true
    resourceGroupName: 'codeconv-rg01'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/SchedulerProcessor/*'
    runtimeStack: 'DOTNET|6.0'
    deploymentMethod: 'auto'

